### ISSUE TITLE
Not support for Windows 10 UWP

### ISSUE THREAD

**Issue by help-14** [borland/SerialQueue#1]
The nugget package is not support for Windows 10 app, I can download the code and build it myself but who don't like nugget, right?

**Comment by borland** [comment]
My apologies for leaving this so long, I was sure it worked. I'll fix it soon hopefully

**Comment by borrrden** [comment]
Just to add to this...if you are already PCL then you should be able to target UWP now for free by bridging to a .NET Standard target.

**Comment by borland** [comment]
The library now supports netstandard2.0 which I believe should work with modern UWP these days
