### ISSUE TITLE
Your code is bad

### ISSUE THREAD

**Issue by gentlee** [borland/SerialQueue#2]
Guys, wash your code in the toilet bowl and look at my true lightweight implementation:

https://github.com/Gentlee/SerialQueue

**Comment by borland** [comment]
Thanks for the feedback

While your implementation is indeed less code than mine, it doesn't support any of these very important features:
- dispatchSync
- delayed invocation (dispatchAfter)
- cancellation

It also works by chaining together tasks with ContinueWith, whereas mine invokes Action()s in a loop. I have no time to benchmark, but as you need to allocate loads of tasks, I'd expect that your "lightweight" approach will have noticeably higher memory usage and slower performance.
Also, I'd check up on the default behaviour of ContinueWith - I think you may be bouncing to another threadpool thread every time you execute a new task, which is going to slow it down tremendously.

Thanks

Orion

**Comment by gentlee** [comment]
Hey @borland, I apologise for my previous harsh statement.

I finally decided to make a benchmark, and also made non-task based implementation. Here are [results](https://github.com/gentlee/SerialQueue#benchmark-results).

Looks like your implementation is working worse than my tasked-based, and a lot worse than my non-task based.

As for "important features" for task-based:
- dispatchSync would be just an API litter because methods return Task, which can be easily awaited synchronously.
- same with dispatchAfter, call can be chained with Task.Delay
- cancellation is a potential improvement, but it can be easily implemented by the caller.

**Comment by borland** [comment]
Hi @gentlee 
I'm not sure why you are coming to me telling me that your code is better than my small hobby project I wrote in 2015. 
I have no objection to you posting benchmarks showing your implementation is faster - that's how software evolves and people learn. 
But rather, do you seek to gain something by sending these messages to me about it? Is there something I can help you with? 
All the best of luck with your future programming endeavours.
